### PR TITLE
Add bracket_spacing rule

### PR DESCRIPTION
**Pull request by danielbayley**
Based on the [`braces_spacing`](https://github.com/aminland/coffeelint2/blob/master/src/rules/braces_spacing.coffee) rule. Closes aminland/coffeelint2#6.

### CODE REVIEW

**Comment by UziTech** [comment]
Currently the way to build the documentation website is broken so I am trying to fix that before we add too many rules.

**Comment by UziTech** [comment]
@danielbayley what is your opinion about adding rules to coffeelint vs telling users to create [3rd party rules](https://github.com/coffeelint/coffeelint/blob/master/3rd_party_rules.md)?

**Comment by danielbayley** [comment]
> @danielbayley what is your opinion about adding rules to coffeelint vs telling users to create [3rd party rules](https://github.com/coffeelint/coffeelint/blob/master/3rd_party_rules.md)?

@UziTech I think obscure rules should be left for 3rd parties. But if the rule has an _[ESLint](https://eslint.org/docs/rules)_ equivalent, then it should go in this repo…

**Comment by UziTech** [comment]
I rebased and merged this

**Pull request closed without merging**
